global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 采集本地 Spring Boot 应用（宿主机）的 Prometheus 指标
  - job_name: "partner-match-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: "partner-match-backend"
